name: Update EduShield Blocklists

on:
  schedule:
    - cron: '0 1 * * *'   # Daily at 01:00 UTC
  workflow_dispatch:       # Manual run button

jobs:
  update-blocklists:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas PyPDF2

      - name: Update and split blocklist
        run: python update_and_split_blocklist.py

      - name: Commit and push updated blocklists
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin "https://${PAT_TOKEN}@github.com/${{ github.repository }}.git"
          git add blocklist.json blocklists/*.json
          git commit -m "Auto-update blocklists + manifest.json (all sources)" || echo "No changes to commit"
          git pull origin main --rebase || echo "No remote changes"
          git push origin HEAD:main --force
        env:
          PAT_TOKEN: ${{ secrets.edushield_token }}
