name: Update EduShield Blocklists

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 01:00 UTC
  workflow_dispatch:

jobs:
  update-blocklists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas PyPDF2

      - name: Run blocklist update script
        run: python update_blocklist.py

      - name: Split blocklist by source
        run: |
          mkdir -p blocklists
          python - <<'EOF'
          import json, os
          with open("blocklist.json", "r", encoding="utf-8") as f:
              data = json.load(f)
          domains = data.get("domains", [])
          grouped = {}
          for entry in domains:
              if isinstance(entry, dict):
                  for src in entry.get("sources") or ["unknown"]:
                      grouped.setdefault(src, []).append(entry)
              else:
                  grouped.setdefault("unknown", []).append({"domain": str(entry), "sources": ["unknown"]})
          os.makedirs("blocklists", exist_ok=True)
          for src, items in grouped.items():
              out_file = f"blocklists/{src.lower().replace(' ', '_')}.json"
              with open(out_file, "w", encoding="utf-8") as f:
                  json.dump({"domains": items}, f, indent=2, ensure_ascii=False)
              print(f"✅ Saved {len(items)} entries to {out_file}")
          EOF

      - name: Generate blocklists/manifest.json
        run: |
          python - <<'EOF'
          import os, json
          files = []
          for f in os.listdir("blocklists"):
              if f.endswith(".json"):
                  source_name = f.replace(".json", "").replace("_", " ").title()
                  files.append({"file": f, "source": source_name})
          with open("blocklists/manifest.json", "w", encoding="utf-8") as mf:
              json.dump({"files": files}, mf, indent=2, ensure_ascii=False)
          print("✅ Generated blocklists/manifest.json")
          EOF

      - name: Commit and push updated blocklists
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin "https://${PAT_TOKEN}@github.com/${{ github.repository }}.git"
          git add blocklist.json blocklists/*.json
          git commit -m "Auto-update blocklists + manifest.json" || echo "No changes to commit"
          git pull origin main --rebase || echo "No remote changes"
          git push origin HEAD:main --force
        env:
          PAT_TOKEN: ${{ secrets.edushield_token }}
